const mongoose = require("mongoose");
const Product = require("../models/Product");

mongoose.connect("mongodb://127.0.0.1:27017/gadgetease", {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

const productCategories = [
  {
    category: "Mouse",
    products: [
      {
        id: "mouse-001",
        name: "Gaming Mouse",
        brand: "Logitech",
        category: "Mouse",
        price: 200,
        week: 500,
        month: 2000,
        security: 200,
        images: [
          "https://images-cdn.ubuy.co.in/633b97e462e47a4eee2183bd-inhanda-wired-rgb-gaming-mouse-high.jpg",
          "https://m.media-amazon.com/images/I/71bhWgQK-cL._AC_SL1500_.jpg",
        ],
        description: "High precision gaming mouse with RGB lighting and ergonomic design.",
      },
      {
        id: "mouse-002",
        name: "Wireless Mouse",
        brand: "Logitech",
        category: "Mouse",
        price: 300,
        week: 600,
        month: 2500,
        security: 300,
        images: [
          "https://m.media-amazon.com/images/I/61LaIVlVOwL._SX679_.jpg",
          "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQN_ALkDpMJkOcT8reDGqT_3JcbjZ4gA5DhvuBzDPxdad_n5YUk_KX5NLMgBkuTQEs0LrKMoLkmpjq1IQvDJzbYFA385KXoJTeK7J8xiOilpjT3-0XJpyl9",
        ],
        description: "Ultra-fast wireless gaming mouse with customizable buttons.",
      },
      {
        id: "mouse-003",
        name: "Ergonomic Mouse",
        brand: "Evofox",
        category: "Mouse",
        price: 400,
        week: 700,
        month: 3000,
        security: 400,
        images: [
          "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTero9rAiVSLrM-LtA5LZOQoEWZhDOzThJAUIg4oWBBEQDbAAdRxNUNuye8Cf17vcxM2kR413LaYYeUWodkCOxqFlP7-iECJUHoYkiSRFN7AZd7dC1PhHcneA",
          "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSkOv13pDV5QFEXjYs-LL0O8nBWp5Ty6Em7kDCOOGBde3mTr247mEEhABPK6OqjdGUDpsLNbGQ2ubgN-Ib1gHbR0IiOGNjb11biF2JFhZXXPVg4IN_AqPRYBQ",
        ],
        description: "Designed for comfort and long working hours.",
      },
      {
        id: "mouse-004",
        name: "Bluetooth Mouse",
        brand: "Microsoft",
        category: "Mouse",
        price: 500,
        week: 800,
        month: 3500,
        security: 500,
        images: [
          "https://m.media-amazon.com/images/I/61EFp6S0fQL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61r08v5bR6L._SX679_.jpg",
        ],
        description: "Wireless Bluetooth mouse with long battery life.",
      },
      {
        id: "mouse-005",
        name: "Silent Click Mouse",
        brand: "Razer",
        category: "Mouse",
        price: 600,
        week: 900,
        month: 4000,
        security: 600,
        images: [
          "https://m.media-amazon.com/images/I/71tdFq8-cML._SX679_.jpg",
          "https://m.media-amazon.com/images/I/6171Osmw0nL._SX679_.jpg",
        ],
        description: "Silent clicking for a noise-free working experience.",
      },
      {
        id: "mouse-006",
        name: "Wired Gaming Mouse",
        brand: "ASUS",
        category: "Mouse",
        price: 700,
        week: 1000,
        month: 4500,
        security: 700,
        images: [
          "https://m.media-amazon.com/images/I/8167lxUe8SL._SY879_.jpg",
          "https://m.media-amazon.com/images/I/81Zt-mjITkL._SX679_.jpg",
        ],
        description: "High DPI wired gaming mouse with customizable RGB.",
      },
      {
        id: "mouse-007",
        name: "Space Wireless Mouse",
        brand: "Connexion",
        category: "Mouse",
        price: 800,
        week: 1100,
        month: 5000,
        security: 800,
        images: [
          "https://m.media-amazon.com/images/I/51Xb48a6hIL._SX679_.jpg",
        ],
        description: "Ultra-lightweight 3D designing mouse for fast movements.",
      },
    ],
  },
  
  {
    category: "Airpods",
    products: [
      {
        id: "airpods-001",
        name: "Apple AirPods Pro",
        brand: "Apple",
        category: "Airpods",
        price: 500,
        week: 1000,
        month: 2200,
        security: 500,
        images: [
          "https://cdn1.smartprix.com/rx-iubNAvq2Y-w420-h420/apple-airpods-pro-3r.webp",
          "https://cdn1.smartprix.com/rx-i37U1jkiB-w420-h420/apple-airpods-pro-3r.webp",
        ],
        description: "Noise-canceling wireless earbuds with superior sound quality.",
      },
      {
        id: "airpods-002",
        name: "Beats Studio Buds",
        brand: "beats",
        category: "Airpods",
        price: 600,
        week: 1200,
        month: 2400,
        security: 600,
        images: [
          "https://m.media-amazon.com/images/I/51qB1-Cs2vL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61WlS6kwHjL._SX679_.jpg",
        ],
        description: "True wireless earbuds with powerful bass and long battery life.",
      },
      {
        id: "airpods-003",
        name: "Bose QuietComfort",
        brand: "Bose",
        category: "Airpods",
        price: 700,
        week: 1400,
        month: 2600,
        security: 700,
        images: [
          "https://m.media-amazon.com/images/I/61rAhXVatbL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/5172tiuKJ5L._SL1200_.jpg",
        ],
        description: "Industry-leading noise-canceling earbuds with rich audio experience.",
      },
      {
        id: "airpods-004",
        name: "Sony wf-1000xm5",
        brand: "Sony",
        category: "Airpods",
        price: 800,
        week: 1600,
        month: 2800,
        security: 800,
        images: [
          "https://m.media-amazon.com/images/I/61GJAFdM9pL._SL1500_.jpg",
          "https://m.media-amazon.com/images/I/91rBRERHmoL._SL1500_.jpg",
        ],
        description: "Comfortable wireless earbuds with deep bass and clear highs.",
      },
      {
        id: "airpods-005",
        name: "Marshall Modtif li ANC",
        brand: "Marshall",
        category: "Airpods",
        price: 900,
        week: 1800,
        month: 3000,
        security: 900,
        images: [
          "https://m.media-amazon.com/images/I/71t+kVzovEL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71Yf97DsCLL._SL1500_.jpg",
        ],
        description: "Pure bass wireless earbuds with fast pairing and long-lasting battery.",
      },
      {
        id: "airpods-006",
        name: "Samsung Galaxy Buds 3",
        brand: "Samsung",
        category: "Airpods",
        price: 1000,
        week: 2000,
        month: 3200,
        security: 1000,
        images: [
          "https://m.media-amazon.com/images/I/71o2C2HqQIL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71QKiqF5q9L._SL1500_.jpg",
        ],
        description: "Compact earbuds with active noise cancellation and spatial audio.",
      },
      {
        id: "airpods-007",
        name: "JBL live Buds 3",
        brand: "JBL",
        category: "Airpods",
        price: 1100,
        week: 2200,
        month: 3400,
        security: 1100,
        images: [
          "https://m.media-amazon.com/images/I/61m12ENe05L._SX679_.jpg",
          "https://m.media-amazon.com/images/I/717d7pe5EEL._SX679_.jpg",
        ],
        description: "Affordable true wireless earbuds with excellent battery life.",
      },
    ],
  },
  
  {
    category: "Headphones",
    products: [
      {
        id: "headphones-001",
        name: "Bose QuietComfort Ultra",
        brand: "Bose",
        category: "Headphones",
        price: 800,
        week: 2000,
        month: 3500,
        security: 800,
        images: [
          "https://m.media-amazon.com/images/I/51yWZxN3vRL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61ARqaLBktL._SX679_.jpg",
        ],
        description: "Premium noise-canceling wireless headphones with immersive sound.",
      },
      {
        id: "headphones-002",
        name: "Marshall Monitor III",
        brand: "Marshall",
        category: "Headphones",
        price: 900,
        week: 2200,
        month: 3700,
        security: 900,
        images: [
          "https://m.media-amazon.com/images/I/81M31hLf2NL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71r+kjb8QYL._SL1500_.jpg",
        ],
        description: "Compact, lightweight earbuds with powerful bass and clear audio.",
      },
      {
        id: "headphones-003",
        name: "Master & Dynamic MG20",
        brand: "Master",
        category: "Headphones",
        price: 1000,
        week: 2400,
        month: 3900,
        security: 1000,
        images: [
          "https://m.media-amazon.com/images/I/51GN9vH0JGL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/81jARtni9OL._SX679_.jpg",
        ],
        description: "Industry-leading noise cancellation for an uninterrupted music experience.",
      },
      {
        id: "headphones-004",
        name: "Apple AirPods Max",
        brand: "Apple",
        category: "Headphones",
        price: 1100,
        week: 2600,
        month: 4100,
        security: 1100,
        images: [
          "https://m.media-amazon.com/images/I/71RJCexaxiL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61Bb9hBUEDL._SX679_.jpg",
        ],
        description: "Comfortable over-ear headphones with exceptional sound clarity.",
      },
      {
        id: "headphones-005",
        name: "Bowers & Wilkins PX8",
        brand: "Bowers",
        category: "Headphones",
        price: 1200,
        week: 2800,
        month: 4300,
        security: 1200,
        images: [
          "https://m.media-amazon.com/images/I/61keweBcgiL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61n1hQYsAJL._SX679_.jpg",
        ],
        description: "Pure bass wireless headphones with long battery life.",
      },
      {
        id: "headphones-006",
        name: "Sennheiser HD 800s",
        brand: "Sennheiser",
        category: "Headphones",
        price: 1300,
        week: 3000,
        month: 4500,
        security: 1300,
        images: [
          "https://m.media-amazon.com/images/I/716RBeOfmDL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/41izlH8QSyL.jpg",
        ],
        description: "Stylish earbuds with active noise cancellation and high-fidelity audio.",
      },
      {
        id: "headphones-007",
        name: "Lightspeed Zulu 3",
        brand: "Lightspeed",
        category: "Headphones",
        price: 1400,
        week: 3200,
        month: 4700,
        security: 1400,
        images: [
          "https://m.media-amazon.com/images/I/41izlH8QSyL.jpg",
          "https://m.media-amazon.com/images/I/61VedFxlbHL._SL1028_.jpg",
        ],
        description: "Affordable true wireless headphones with immersive bass and crisp sound.",
      },
    ],
  },

  {
    category: "Mobiles",
    products: [
      {
        id: "mobile-001",
        name: "iPhone 16 Pro Max",
        brand: "Apple",
        category: "Mobiles",
        price: 1500,
        week: 5000,
        month: 10000,
        security: 1000,
        images: [
          "https://m.media-amazon.com/images/I/619oqSJVY5L._SX679_.jpg",
          "https://m.media-amazon.com/images/I/81bkUCHTJTL._SX679_.jpg",
        ],
        description: "Apple's flagship smartphone with A16 Bionic chip and ProMotion display.",
      },
      {
        id: "mobile-002",
        name: "Samsung Galaxy S25 Ultra",
        brand: "Samsung",
        category: "Mobiles",
        price: 1700,
        week: 6000,
        month: 12000,
        security: 1100,
        images: [
          "https://m.media-amazon.com/images/I/71P85R392uL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71pfjBJUA7L._SL1500_.jpg",
        ],
        description: "Samsung's premium smartphone with a 200MP camera and S-Pen support.",
      },
      {
        id: "mobile-003",
        name: "Google Pixel 9 Pro",
        brand: "Google",
        category: "Mobiles",
        price: 1900,
        week: 7000,
        month: 14000,
        security: 1200,
        images: [
          "https://m.media-amazon.com/images/I/319eh0vlEbL.jpg",
        ],
        description: "Google's AI-powered smartphone with best-in-class photography and Tensor G2 chip.",
      },
      {
        id: "mobile-004",
        name: "OnePlus 13 R",
        brand: "OnePlus",
        category: "Mobiles",
        price: 2100,
        week: 8000,
        month: 16000,
        security: 1300,
        images: [
          "https://m.media-amazon.com/images/I/61++T836jiL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71rPMsQJv2L._SX679_.jpg",
        ],
        description: "Flagship OnePlus device with 120Hz AMOLED display and Snapdragon 8 Gen 2 processor.",
      },
      {
        id: "mobile-005",
        name: "Xiaomi 15 Ultra",
        brand: "Xiaomi",
        category: "Mobiles",
        price: 2300,
        week: 10000,
        month: 20000,
        security: 1400,
        images: [
          "https://m.media-amazon.com/images/I/81ql3U3xAwL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/812BBZnCIPL._SX679_.jpg",
        ],
        description: "Xiaomi's premium device with Leica cameras and super-fast charging.",
      },
      {
        id: "mobile-006",
        name: "Realme GT 7 Pro",
        brand: "Realme",
        category: "Mobiles",
        price: 2500,
        week: 12000,
        month: 24000,
        security: 1500,
        images: [
          "https://m.media-amazon.com/images/I/71rFJVZsNNL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/81HtQmAsX0L._SL1500_.jpg",
        ],
        description: "High-performance gaming phone with 240W charging and Snapdragon 8+ Gen 1.",
      },
      {
        id: "mobile-007",
        name: "Asus ROG Phone 9 Pro",
        brand: "Asus",
        category: "Mobiles",
        price: 2700,
        week: 14000,
        month: 28000,
        security: 1600,
        images: [
          "https://m.media-amazon.com/images/I/81qtCkPIzhL._AC_SX679_.jpg",
          "https://m.media-amazon.com/images/I/81BByqNeiAL._AC_SX679_.jpg",
        ],
        description: "The ultimate gaming phone with 165Hz display and AirTrigger controls.",
      },
    ],
  },

  {
    category: "Watches",
    products: [
      {
        id: "watch-001",
        name: "Apple Watch Ultra 2",
        brand: "Apple",
        category: "Watches",
        price: 1600,
        week: 4000,
        month: 6000,
        security: 1000,
        images: [
          "https://m.media-amazon.com/images/I/81CUXO9xeHL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/81CUXO9xeHL._SX679_.jpg",
        ],
        description: "Advanced smartwatch with health tracking, always-on display, and seamless Apple ecosystem integration.",
      },
      {
        id: "watch-002",
        name: "Samsung Galaxy Watch Ultra",
        brand: "Samsung",
        category: "Watches",
        price: 1700,
        week: 4500,
        month: 7000,
        security: 1100,
        images: [
          "https://m.media-amazon.com/images/I/81WgHy3pZ3L._SX679_.jpg",
        ],
        description: "Premium smartwatch with AMOLED display, fitness tracking, and Wear OS support.",
      },
      {
        id: "watch-003",
        name: "Withings ScanWatch",
        brand: "Withings",
        category: "Watches",
        price: 1800,
        week: 5000,
        month: 8000,
        security: 1200,
        images: [
          "https://m.media-amazon.com/images/I/81WgHy3pZ3L._SX679_.jpg",
        ],
        description: "Ultimate outdoor smartwatch with GPS navigation, long battery life, and rugged design.",
      },
      {
        id: "watch-004",
        name: "Google Pixel Watch 3",
        brand: "Google",
        category: "Watches",
        price: 1900,
        week: 5500,
        month: 9000,
        security: 1300,
        images: [
          "https://m.media-amazon.com/images/I/61HCdYMr9UL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61HCdYMr9UL._SX679_.jpg",
        ],
        description: "Smartwatch with ECG, stress tracking, sleep monitoring, and Fitbit ecosystem integration.",
      },
      {
        id: "watch-005",
        name: "Amazfit GTR 4",
        brand: "Amazfit",
        category: "Watches",
        price: 2000,
        week: 6000,
        month: 10000,
        security: 1400,
        images: [
          "https://m.media-amazon.com/images/I/71tJuWCYKyL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61yXEFGP3tL._SX679_.jpg",
        ],
        description: "Stylish smartwatch with advanced fitness tracking, GPS, and long battery life.",
      },
      {
        id: "watch-006",
        name: "Fitbit Blaze",
        brand: "Fitbit",
        category: "Watches",
        price: 2100,
        week: 6500,
        month: 11000,
        security: 1500,
        images: [
          "https://m.media-amazon.com/images/I/516bRCMqzPL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/516bRCMqzPL._SX679_.jpg",
        ],
        description: "Sleek smartwatch with AMOLED display, sports tracking, and premium build quality.",
      },
      {
        id: "watch-007",
        name: "Fossil Gen 6",
        brand: "Fossil",
        category: "Watches",
        price: 2200,
        week: 7000,
        month: 12000,
        security: 1600,
        images: [
          "https://m.media-amazon.com/images/I/51yI829dMoL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/51SF-2dX9EL._SX679_.jpg",
        ],
        description: "Fashionable Wear OS smartwatch with fast charging and customizable watch faces.",
      },
    ],
  },
  
  {
    category: "Cameras",
    products: [
      {
        id: "cam-001",
        name: "Canon EOS R5",
        brand: "Canon",
        category: "Cameras",
        price: 1000,
        week: 5000,
        month: 10000,
        security: 800,
        images: [
          "https://m.media-amazon.com/images/I/61vm45CsUHL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/51uBd2w+PzL._SX679_.jpg",
        ],
        description: "High-resolution mirrorless camera with 8K video recording and advanced autofocus.",
      },
      {
        id: "cam-002",
        name: "Sony Alpha II",
        brand: "Sony",
        category: "Cameras",
        price: 1200,
        week: 6000,
        month: 12000,
        security: 900,
        images: [
          "https://m.media-amazon.com/images/I/71j3bPnm+UL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/81vQst9IHDL._SX679_.jpg",
        ],
        description: "Versatile full-frame camera with exceptional image quality and 4K 60p video.",
      },
      {
        id: "cam-003",
        name: "Nikon Z9",
        brand: "Nikon",
        category: "Cameras",
        price: 1400,
        week: 7000,
        month: 13000,
        security: 1000,
        images: [
          "https://m.media-amazon.com/images/I/81XPdr-4d6L._SX679_.jpg",
          "https://m.media-amazon.com/images/I/5154l9U5iRL._SX679_.jpg",
        ],
        description: "Professional mirrorless camera with fast autofocus and 120fps burst shooting.",
      },
      {
        id: "cam-004",
        name: "Fujifilm X-T5",
        brand: "Fujifilm",
        category: "Cameras",
        price: 1600,
        week: 8000,
        month: 15000,
        security: 1100,
        images: [
          "https://m.media-amazon.com/images/I/61K4pvZnmML._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61K4pvZnmML._SX679_.jpg",
        ],
        description: "Retro-style APS-C camera with 40MP sensor and in-body stabilization.",
      },
      {
        id: "cam-005",
        name: "Panasonic AG CX7",
        brand: "Panasonic",
        category: "Cameras",
        price: 1800,
        week: 9000,
        month: 17000,
        security: 1200,
        images: [
          "https://m.media-amazon.com/images/I/41NiHBT8+9L.jpg",
        ],
        description: "Hybrid mirrorless camera with exceptional video capabilities and 5-axis stabilization.",
      },
      {
        id: "cam-006",
        name: "GoPro HERO12 Black",
        brand: "GoPro",
        category: "Cameras",
        price: 2000,
        week: 10000,
        month: 19000,
        security: 1300,
        images: [
          "https://m.media-amazon.com/images/I/615eTO83jLL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/81f9HXUeeZL._SX679_.jpg",
      ],
        description: "Action camera with 5.3K video recording, waterproof design, and stabilization.",
      },
      {
        id: "cam-007",
        name: "DJI Osmo Action 5 Pro",
        brand: "DJI",
        category: "Cameras",
        price: 2200,
        week: 11000,
        month: 21000,
        security: 1400,
        images: [
          "https://m.media-amazon.com/images/I/51cNLXI9iUL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61PSd-ydoFL._SX679_.jpg",
        ],
        description: "Compact gimbal camera with 4K HDR video and AI-powered tracking.",
      },
    ],
  },

  {
    category: "Speakers",
    products: [
      {
        id: "spk-001",
        name: "TRONICA Dual Launched Thunder Vibra",
        brand: "Tronica",
        category: "Speakers",
        price: 2000,
        week: 6000,
        month: 10000,
        security: 1000,
        images: [
          "https://m.media-amazon.com/images/I/810JLjFduVL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/91X-jLyNCeL._SX679_.jpg",
        ],
        description: "Portable Bluetooth speaker with 360-degree sound and water-resistant design.",
      },
      {
        id: "spk-002",
        name: "Yamaha Stagepas 400BT",
        brand: "Yamaha",
        category: "Speakers",
        price: 2200,
        week: 7000,
        month: 11000,
        security: 1100,
        images: [
          "https://m.media-amazon.com/images/I/71Y0jcZivtL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71Y0jcZivtL._SX679_.jpg"
      ],
        description: "Waterproof Bluetooth speaker with powerful bass and long battery life.",
      },
      {
        id: "spk-003",
        name: "Samsung 656",
        brand: "Samsung",
        category: "Speakers",
        price: 2400,
        week: 8000,
        month: 12000,
        security: 1200,
        images: [
          "https://m.media-amazon.com/images/I/71h-lHKoKhL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71CzFzfdMUL._SX679_.jpg",
        ],
        description: "Wireless speaker with extra bass, LED lights, and 24-hour battery life.",
      },
      {
        id: "spk-004",
        name: "Atoz Stone",
        brand: "Atoz",
        category: "Speakers",
        price: 2500,
        week: 9000,
        month: 14000,
        security: 1300,
        images: [
          "https://m.media-amazon.com/images/I/61ItbD9e5jL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61vReuRcZ2L._SX679_.jpg",
        ],
        description: "Classic design Bluetooth speaker with rich sound and durable build.",
      },
      {
        id: "spk-005",
        name: "JBL Professional",
        brand: "Ultimate Ears",
        category: "Speakers",
        price: 2600,
        week: 10000,
        month: 15000,
        security: 1400,
        images: [
          "https://m.media-amazon.com/images/I/61D1RP8fJGL._SY879_.jpg",
          "https://m.media-amazon.com/images/I/51kL80CBLzL._SY879_.jpg",
        ],
        description: "Rugged and waterproof speaker with 360-degree sound and deep bass.",
      },
      {
        id: "spk-006",
        name: "JBL PartyBox Unlimted",
        brand: "JBL",
        category: "Speakers",
        price: 2700,
        week: 11000,
        month: 16000,
        security: 1500,
        images: [
          "https://m.media-amazon.com/images/I/81TdqUkessL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/81-b0OzcLrL._SX679_.jpg",
        ],
        description: "Smart speaker with voice assistant support and Wi-Fi/Bluetooth connectivity.",
      },
      {
        id: "spk-007",
        name: "Sony Bravia Theatre Quad",
        brand: "Sony",
        category: "Speakers",
        price: 2800,
        week: 12000,
        month: 17000,
        security: 1600,
        images: [
          "https://m.media-amazon.com/images/I/81-b0OzcLrL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61-oOI1GEgL._SX679_.jpg",
        ],
        description: "Premium speaker with dual tweeters for immersive stereo sound.",
      },
    ],
  },

  {
    category: "Laptops",
    products: [
      {
        id: "laptop-001",
        name: "Apple MacBook Pro Air",
        brand: "Apple",
        category: "Laptops",
        price: 2500,
        week: 5000,
        month: 10000,
        security: 1500,
        images: [
          "https://m.media-amazon.com/images/I/71pKJ+Mjd8L._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61ovNoIFFsL._SX679_.jpg",
        ],
        description: "Powerful MacBook with M3 chip, Retina display, and exceptional battery life.",
      },
      {
        id: "laptop-002",
        name: "Asus TUF Gaming",
        brand: "ASUS",
        category: "Laptops",
        price: 2700,
        week: 6000,
        month: 12000,
        security: 1600,
        images: [
          "https://m.media-amazon.com/images/I/71pVO1U9oeL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/81CiOltXy8L._SX679_.jpg",
        ],
        description: "Sleek and powerful laptop with a stunning 4K OLED display and Intel Core i9 processor.",
      },
      {
        id: "laptop-003",
        name: "ASUS ROG Zephyrus",
        brand: "ASUS",
        category: "Laptops",
        price: 2900,
        week: 7000,
        month: 14000,
        security: 1700,
        images: [
          "https://m.media-amazon.com/images/I/715jUeWInhL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71A5+SSAE1L._SX679_.jpg",
        ],
        description: "Convertible touchscreen laptop with a stylish design and long battery life.",
      },
      {
        id: "laptop-004",
        name: "Dell Alienware m18 R1",
        brand: "Dell",
        category: "Laptops",
        price: 3100,
        week: 8000,
        month: 16000,
        security: 1800,
        images: [
          "https://m.media-amazon.com/images/I/71BxDqP7L5L._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61pD7PopYkL._SX679_.jpg",
        ],
        description: "High-performance gaming laptop with Ryzen 9 processor and RTX 4070 graphics.",
      },
      {
        id: "laptop-005",
        name: "Lenovo Yoga Slim 7",
        brand: "Lenovo",
        category: "Laptops",
        price: 3300,
        week: 9000,
        month: 18000,
        security: 1900,
        images: [
          "https://m.media-amazon.com/images/I/61ZxrrWZLtL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71oMtACKyVL._SX679_.jpg",
        ],
        description: "Business-class ultrabook with a durable build and top-notch security features.",
      },
      {
        id: "laptop-006",
        name: "HP Firefly",
        brand: "HP",
        category: "Laptops",
        price: 3500,
        week: 10000,
        month: 20000,
        security: 2000,
        images: [
          "https://m.media-amazon.com/images/I/41cox519+vL.jpg",
          "https://m.media-amazon.com/images/I/41cox519+vL.jpg",
        ],
        description: "Lightweight touchscreen laptop with premium design and excellent battery life.",
      },
      {
        id: "laptop-007",
        name: "MSI Katana",
        brand: "MSI",
        category: "Laptops",
        price: 3700,
        week: 11000,
        month: 22000,
        security: 2100,
        images: [
          "https://m.media-amazon.com/images/I/71RgcZjmLBL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71RgcZjmLBL._SX679_.jpg",
        ],
        description: "Gaming laptop with high refresh rate display and advanced cooling technology.",
      },
    ],
  },

  {
    category: "Television",
    products: [
      {
        id: "tv-001",
        name: "Sony Bravia 3",
        brand: "Sony",
        category: "Television",
        price: 2000,
        week: 5000,
        month: 10000,
        security: 1500,        
        images: [
          "https://m.media-amazon.com/images/I/81h-r-3hioL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/81uanf9+vDL._SX679_.jpg",
        ],
        description: "4K Smart TV with Quantum Dot technology for brilliant colors and HDR support.",
      },
      {
        id: "tv-002",
        name: "Hisense Q7N",
        brand: "Hisense",
        category: "Television",
        price: 2200,
        week: 6000,
        month: 12000,
        security: 1600,
        images: [
          "https://m.media-amazon.com/images/I/81pP5Fyo7-L._SX679_.jpg",
          "https://m.media-amazon.com/images/I/713PyAVIjDL._SX679_.jpg",
        ],
        description: "Premium OLED TV with deep blacks, Dolby Vision, and 120Hz refresh rate.",
      },
      {
        id: "tv-003",
        name: "Toshiba C450NP",
        brand: "Toshiba",
        category: "Television",
        price: 2400,
        week: 7000,
        month: 14000,
        security: 1700,
        images: [
          "https://m.media-amazon.com/images/I/81Qi3Y6yxEL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/814mPhj0+DL._SX679_.jpg",
        ],
        description: "Cutting-edge QD-OLED TV with Cognitive Processor XR for immersive visuals.",
      },
      {
        id: "tv-004",
        name: "TCL C655",
        brand: "TCL",
        category: "Television",
        price: 2600,
        week: 8000,
        month: 16000,
        security: 1800,
        images: [
          "https://m.media-amazon.com/images/I/71TauqUY-XL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/81C1PkQws9L._SX679_.jpg",
        ],
        description: "Affordable 4K TV with Mini-LED backlighting and Dolby Vision support.",
      },
      {
        id: "tv-005",
        name: "Samsung 4K Ultra HD Smart Neo QLED",
        brand: "Samsung",
        category: "Television",
        price: 2800,
        week: 9000,
        month: 18000,
        security: 1900,
        images: [
          "https://m.media-amazon.com/images/I/91b1B9Pjd2L._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61ttcCPtvDL._SX679_.jpg",
        ],
        description: "High-performance ULED TV with 1000+ nits brightness and gaming features.",
      },
      {
        id: "tv-006",
        name: "Hisense Trichrom ALR Series",
        brand: "Hisense",
        category: "Television",
        price: 3000,
        week: 10000,
        month: 20000,
        security: 2000,
        images: [
          "https://m.media-amazon.com/images/I/91o-7+jHqFL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71eh6UmfAFL._SX679_.jpg",
        ],
        description: "4K HDR TV with superior contrast and advanced full-array local dimming.",
      },
      {
        id: "tv-007",
        name: "NEOD 4K UHD Touch Screen LED TV",
        brand: "NEOD",
        category: "Television",
        price: 3200,
        week: 11000,
        month: 22000,
        security: 2100,
        images: [
          "https://m.media-amazon.com/images/I/51dtimEZTnL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61PHECylfaL._SX679_.jpg",
        ],
        description: "Cinema-quality OLED TV with Hollywood-tuned color accuracy and Dolby Atmos.",
      },
    ],
  },

  {
    category: "Washingmachines",
    products: [
      {
        id: "wm-001",
        name: "LG Smart Inverter Technology",
        brand: "LG",
        category: "Washingmachines",
        price: 2000,
        week: 5000,
        month: 8000,
        security: 1000,
        images: [
          "https://m.media-amazon.com/images/I/71l+EeVZypL._SY879_.jpg",
          "https://m.media-amazon.com/images/I/71l+EeVZypL._SY879_.jpg",
        ],
        description: "High-efficiency front-load washing machine with inverter technology and steam wash.",
      },
      {
        id: "wm-002",
        name: "Samsung Eco Bubble Tech",
        brand: "Samsung",
        category: "Washingmachines",
        price: 2200,
        week: 6000,
        month: 10000,
        security: 1100,
        images: [
          "https://m.media-amazon.com/images/I/61wstFqAjyL._SY879_.jpg",
          "https://m.media-amazon.com/images/I/71ehdobjeiL._SX679_.jpg",
        ],
        description: "Fully automatic top-load washing machine with powerful cleaning and eco bubble technology.",
      },
      {
        id: "wm-003",
        name: "Bosch Fully-Automatic Washingmachine",
        brand: "Bosch",
        category: "Washingmachines",
        price: 2400,
        week: 7000,
        month: 12000,
        security: 1200,
        images: [
          "https://m.media-amazon.com/images/I/61ME1uI2+fL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71jdfwcG4EL._SX679_.jpg",
        ],
        description: "Energy-efficient washing machine with anti-vibration design and speed wash feature.",
      },
      {
        id: "wm-004",
        name: "Whirlpool 5 MAGIC CLEAN PRO SW H",
        brand: "Whirlpool",
        category: "Washingmachines",
        price: 2600,
        week: 8000,
        month: 14000,
        security: 1300,
        images: [
          "https://m.media-amazon.com/images/I/71QiAjw7KdL._SY879_.jpg",
          "https://m.media-amazon.com/images/I/71lkXCerhAL._SX679_.jpg",
        ],
        description: "Budget-friendly semi-automatic washing machine with turbo scrubbing and lint filter.",
      },
      {
        id: "wm-005",
        name: "IFB Powered by AI with 9 Swirl Wash",
        brand: "IFB",
        category: "Washingmachines",
        price: 2800,
        week: 9000,
        month: 16000,
        security: 1400,
        images: [
          "https://m.media-amazon.com/images/I/61MrJ+ANEcL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61BZjAco-vL._SX679_.jpg",
        ],
        description: "Premium front-load washing machine with 3D wash system and crescent moon drum.",
      },
      {
        id: "wm-006",
        name: "Panasonic 7kg Top Load Washing Machine",
        brand: "Panasonic",
        category: "Washingmachines",
        price: 3000,
        week: 10000,
        month: 18000,
        security: 1500,
        images: [
          "https://m.media-amazon.com/images/I/71E02iGZyzL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71E02iGZyzL._SX679_.jpg",
        ],
        description: "Advanced washing machine with Aqua Beat wash and one-touch operation.",
      },
      {
        id: "wm-007",
        name: "Voltas Beko, A Tata Product",
        brand: "Voltas",
        category: "Washingmachines",
        price: 3200,
        week: 11000,
        month: 20000,
        security: 1600,
        images: [
          "https://m.media-amazon.com/images/I/71jvpjtdCEL._SY879_.jpg",
          "https://m.media-amazon.com/images/I/81WZFox8GPL._SX679_.jpg",
        ],
        description: "Smart inverter technology with anti-bacterial wash and energy-saving mode.",
      },
    ],
  },

  {
    category: "AC",
    products: [
      {
        id: "ac-001",
        name: "LG DUAL Inverter Split AC ",
        brand: "LG",
        category: "AC",
        price: 3000,
        week: 6000,
        month: 10000,
        security: 1500,
        images: [
          "https://m.media-amazon.com/images/I/814uYcqrtoL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/81ZHEOtj43L._SX679_.jpg",
        ],
        description: "High-performance inverter AC with AI dual inverter compressor and low noise.",
      },
      {
        id: "ac-002",
        name: "Hitachi Wifi-enabled, Inverter Split AC",
        brand: "Hitachi",
        category: "AC",
        price: 3200,
        week: 7000,
        month: 10000,
        security: 1600,
        images: [
          "https://m.media-amazon.com/images/I/511qaYsns6L._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71o4voEf2mL._SX679_.jpg",
        ],
        description: "Energy-efficient split AC with fast cooling mode and anti-bacterial filter.",
      },
      {
        id: "ac-003",
        name: "Daikin Inverter Split AC",
        brand: "Daikin",
        category: "AC",
        price: 3400,
        week: 8000,
        month: 12000,
        security: 1700,
        images: [
          "https://m.media-amazon.com/images/I/61JyEPdw3UL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61JyEPdw3UL._SX679_.jpg",
        ],
        description: "Powerful air conditioner with PM2.5 filter and Coanda airflow for uniform cooling.",
      },
      {
        id: "ac-004",
        name: "Panasonic Wi-Fi Inverter Smart Split AC",
        brand: "Panasonic",
        category: "AC",
        price: 3600,
        week: 10000,
        month: 14000,
        security: 1800,
        images: [
          "https://m.media-amazon.com/images/I/61h5jbbjXIL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/81XmzRdiTmL._SX679_.jpg",
        ],
        description: "Durable window AC with auto climate technology and copper condenser.",
      },
      {
        id: "ac-005",
        name: "Voltas Split AC",
        brand: "Voltas",
        category: "AC",
        price: 3800,
        week: 11000,
        month: 16000,
        security: 1900,
        images: [
          "https://m.media-amazon.com/images/I/51hjt2Tw54L._SX679_.jpg",
          "https://m.media-amazon.com/images/I/6150+1s1tuL._SX679_.jpg",
        ],
        description: "Affordable and efficient AC with turbo cooling and active dehumidifier.",
      },
      {
        id: "ac-006",
        name: "Godrej 5-In-1, Wood Finish, AC",
        brand: "Godrej",
        category: "AC",
        price: 4000,
        week: 12000,
        month: 18000,
        security: 2000,
        images: [
          "https://m.media-amazon.com/images/I/6150+1s1tuL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/6150+1s1tuL._SX679_.jpg",
        ],
        description: "Smart AC with precision cooling technology and iFeel remote control.",
      },
      {
        id: "ac-007",
        name: "Carrier Wi-Fi Smart Flexicool Inverter Split AC",
        brand: "Carrier",
        category: "AC",
        price: 4200,
        week: 13000,
        month: 20000,
        security: 2100,
        images: [
          "https://m.media-amazon.com/images/I/81Jec1au1rL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/81ip2D7GKxL._SX679_.jpg",
        ],
        description: "Best-in-class AC with high cooling capacity and dust filter for fresh air.",
      },
    ],
  },  

  {
    category: "Microwave",
    products: [
      {
        id: "mw-001",
        name: "LG 28L Convection Microwave Oven",
        brand: "LG",
        category: "Microwave",
        price: 2000,
        week: 5000,
        month: 8000,
        security: 1000,
        images: [
          "https://m.media-amazon.com/images/I/61xM+QwcTzL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/81zOBeUxAXL._SX679_.jpg",
        ],
        description: "A high-capacity convection microwave with auto-cook and smart inverter technology.",
      },
      {
        id: "mw-002",
        name: "Carysil MWO-02 Fully Automatic ",
        brand: "Carysil",
        category: "Microwave",
        price: 2200,
        week: 6000,
        month: 10000,
        security: 1100,
        images: [
          "https://m.media-amazon.com/images/I/51sQeTaiwjL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71rNJJjuXyL._SX679_.jpg"
        ],
        description: "Compact and efficient microwave oven with ceramic enamel interior for easy cleaning.",
      },
      {
        id: "mw-003",
        name: "Bosch 6 Built-In Microwave Oven",
        brand: "Bosch",
        category: "Microwave",
        price: 2400,
        week: 7000,
        month: 12000,
        security: 1200,
        images: [
          "https://m.media-amazon.com/images/I/61gdlogoHDL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/610grslKBNL._SX679_.jpg",
        ],
        description: "Feature-packed microwave with multi-stage cooking, grill mode, and child lock.",
      },
      {
        id: "mw-004",
        name: "Faber Built-In Touch Control",
        brand: "Faber",
        category: "Microwave",
        price: 2600,
        week: 8000,
        month: 14000,
        security: 1300,
        images: [
          "https://m.media-amazon.com/images/I/71dWASZ60gL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71GKde+DIgL._SX679_.jpg",
        ],
        description: "Compact microwave ideal for reheating and defrosting with intuitive controls.",
      },
      {
        id: "mw-005",
        name: "Samsung Convection Microwave Oven",
        brand: "Samsung",
        category: "Microwave",
        price: 2800,
        week: 9000,
        month: 16000,
        security: 1400,
        images: [
          "https://m.media-amazon.com/images/I/519N7fdNBEL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/41NXStxba3L._SX679_.jpg",
        ],
        description: "Powerful grill microwave oven with smart cooking modes and 10 power levels.",
      },
      {
        id: "mw-006",
        name: "Westinghouse Counter Top",
        brand: "Westinghouse",
        category: "Microwave",
        price: 3000,
        week: 10000,
        month: 18000,
        security: 1500,
        images: [
          "https://m.media-amazon.com/images/I/71RjYcgIbzL._SY879_.jpg",
          "https://m.media-amazon.com/images/I/81lTyI4aTxL._SY879_.jpg",
        ],
        description: "Eco-friendly convection microwave with steam clean function and healthy fry technology.",
      },
      {
        id: "mw-007",
        name: "Hindware Smart Appliances ",
        brand: "Hindware",
        category: "Microwave",
        price: 3200,
        week: 11000,
        month: 20000,
        security: 1600,
        images: [
          "https://m.media-amazon.com/images/I/51Ou4B2JvSL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61Qk9okeUeL._SX679_.jpg",
        ],
        description: "Affordable and efficient microwave oven with a mechanical knob and timer.",
      },
    ],
  },

  {
    category: "Juicer",
    products: [
      {
        id: "juicer-001",
        name: "Kuvings CS600 ",
        brand: "Kuvings",
        category: "Juicer",
        price: 1800,
        week: 5000,
        month: 8000,
        security: 900,
        images: [
          "https://m.media-amazon.com/images/I/717gWnkyzcL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71ZF87+1zZL._SX679_.jpg",
        ],
        description: "Powerful centrifugal juicer with quick-clean technology and drip-stop feature.",
      },
      {
        id: "juicer-002",
        name: "Cold Press Touchscreen",
        brand: "Evoloop",
        category: "Juicer",
        price: 2000,
        week: 6000,
        month: 9000,
        security: 1000,
        images: [
          "https://m.media-amazon.com/images/I/71aN3rPc5VL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71pYL7lefBL._SX679_.jpg",
        ],
        description: "High-speed juicer with dual-speed control and stainless steel filter.",
      },
      {
        id: "juicer-003",
        name: "Philips Viva Collection HR1832/00",
        brand: "Philips",
        category: "Juicer",
        price: 2100,
        week: 7000,
        month: 10000,
        security: 1100,
        images: [
          "https://m.media-amazon.com/images/I/710awFfJbwL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61rPedd7y6L._SX679_.jpg",
        ],
        description: "Commercial-grade juicer with 900W motor and shock-proof body.",
      },
      {
        id: "juicer-004",
        name: "NutriPro Juicer Mixer Grinder",
        brand: "NutriPro",
        category: "Juicer",
        price: 2200,
        week: 8000,
        month: 11000,
        security: 1200,
        images: [
          "https://m.media-amazon.com/images/I/71PkRff5mdL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71XhtcD47XL._SX679_.jpg",
        ],
        description: "Multipurpose juicer and mixer with easy pulp removal and 2-speed control.",
      },
      {
        id: "juicer-005",
        name: "Havells Hexo",
        brand: "Havells",
        category: "Juicer",
        price: 2300,
        week: 9000,
        month: 11000,
        security: 1300,
        images: [
          "https://m.media-amazon.com/images/I/61CgakOpj-L._SX679_.jpg",
        ],
        description: "Cold press juicer with low-speed extraction for maximum nutrient retention.",
      },
      {
        id: "juicer-006",
        name: "Maharaja Whiteline Odacio Plus",
        brand: "Maharaja",
        category: "Juicer",
        price: 2400,
        week: 10000,
        month: 12000,
        security: 1400,
        images: [
          "https://m.media-amazon.com/images/I/51Ix68mAvVL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/61r8cu8M7AL._SX679_.jpg",
        ],
        description: "Premium slow juicer with a wide feeding tube and high juice yield.",
      },
      {
        id: "juicer-007",
        name: "Havells Vitonica",
        brand: "Havells",
        category: "Juicer",
        price: 2500,
        week: 11000,
        month: 13000,
        security: 1500,
        images: [
          "https://m.media-amazon.com/images/I/710qWSSMEsL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/51CA7S0Sq5L.jpg",
        ],
        description: "Quiet and efficient cold press juicer with a large pulp container and juice jug.",
      },
    ],
  },  
  
  {
    category: "Refrigerator",
    products: [
      {
        id: "rf-001",
        name: "LG 655 Double Door Side by Side Refrigerator",
        brand: "LG",
        category: "Refrigerator",
        price: 2000,
        week: 6000,
        month: 8000,
        security: 1000,
        images: [
          "https://m.media-amazon.com/images/I/61t3vCqx6CL._SY879_.jpg",
          "https://m.media-amazon.com/images/I/81WACOVji5L._SX679_.jpg",
        ],
        description: "Frost-free double door refrigerator with smart inverter compressor for energy efficiency.",
      },
      {
        id: "rf-002",
        name: "Samsung 236 Double Door Refrigerator",
        brand: "Samsung",
        category: "Refrigerator",
        price: 2100,
        week: 7000,
        month: 10000,
        security: 1100,
        images: [
          "https://m.media-amazon.com/images/I/61ZX+36YjmL._SY879_.jpg",
          "https://m.media-amazon.com/images/I/81s99Ov-FBL._SX679_.jpg",
        ],
        description: "Large-capacity refrigerator with Digital Inverter technology and built-in deodorizer.",
      },
      {
        id: "rf-003",
        name: "Whirlpool 292 Frost Free Refrigerator",
        brand: "Whirlpool",
        category: "Refrigerator",
        price: 2200,
        week: 8000,
        month: 12000,
        security: 1200,
        images: [
          "https://m.media-amazon.com/images/I/81afSsSwiXL._SY879_.jpg",
          "https://m.media-amazon.com/images/I/71JYpOz5A9S._SX679_.jpg",
        ],
        description: "Stylish frost-free refrigerator with IntelliSense inverter technology and fast cooling.",
      },
      {
        id: "rf-004",
        name: "Godrej 472 with AI Tech",
        brand: "Godrej",
        category: "Refrigerator",
        price: 2300,
        week: 9000,
        month: 14000,
        security: 1300,
        images: [
          "https://m.media-amazon.com/images/I/51p8TV6V93L._SX679_.jpg",
          "https://m.media-amazon.com/images/I/81PqMVuA8UL._SX679_.jpg",
        ],
        description: "Affordable single-door refrigerator with an anti-bacterial gasket and toughened glass shelves.",
      },
      {
        id: "rf-005",
        name: "Haier Convertible Fridge",
        brand: "Haier",
        category: "Refrigerator",
        price: 2400,
        week: 10000,
        month: 16000,
        security: 1400,
        images: [
          "https://m.media-amazon.com/images/I/71Ul4+d-hyL._SL1500_.jpg",
          "https://m.media-amazon.com/images/I/81BNVI9uPbL._SL1500_.jpg",
        ],
        description: "Innovative bottom-mounted freezer with 1-hour icing technology and energy efficiency.",
      },
      {
        id: "rf-006",
        name: "Panasonic 336L Multi-Door Refrigerator",
        brand: "Panasonic",
        category: "Refrigerator",
        price: 2500,
        week: 11000,
        month: 18000,
        security: 1500,
        images: [
          "https://m.media-amazon.com/images/I/71UMrrxn4SL._AC_CR0%2C0%2C0%2C0_SX615_SY462_.jpg",
          "https://m.media-amazon.com/images/I/71dYrSD18tL._AC_CR0%2C0%2C0%2C0_SX615_SY462_.jpg",
        ],
        description: "Multi-door refrigerator with AG clean technology for bacteria-free storage.",
      },
      {
        id: "rf-007",
        name: "Whirlpool Frost Free",
        brand: "Whirlpool",
        category: "Refrigerator",
        price: 2600,
        week: 12000,
        month: 20000,
        security: 1600,
        images: [
          "https://m.media-amazon.com/images/I/61aJHNXpzeL._SX679_.jpg",
          "https://m.media-amazon.com/images/I/71eibZkBclL._SX679_.jpg",
        ],
        description: "Premium side-by-side refrigerator with VitaFresh technology and spacious compartments.",
      },
    ],
  },

];

// **Flattening Data**
const products = productCategories.flatMap((categoryData) =>
  categoryData.products.map((product) => ({
    ...product,
    category: categoryData.category, // Add category field to each product
  }))
);

// Function to Insert Products
const insertProducts = async () => {
  try {
    await Product.deleteMany(); // Clear existing data
    for (const category of productCategories) {
      for (const product of category.products) {
        await Product.create(product);
      }
    }
    console.log("✅ Products added successfully!");
    mongoose.connection.close();
  } catch (error) {
    console.error("❌ Error inserting products:", error);
    mongoose.connection.close();
  }
};

insertProducts();
